version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.27.0@sha256:4da2d4b4e216276b51c2a8765aad89e3e676ef17097d00684cab6a013df94ed9
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml -- -race -coverprofile=coverage.txt -covermode=atomic $(go list ./... | grep -v internal/filesystem/mocks)
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash) -f coverage.txt
      - store_test_results:
          path: /tmp/test-reports

workflows:
  build-test:
    jobs:
      - build
